name: JS

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

env:
  FORCE_COLOR: 2
  NODE: 22

jobs:
  js:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jquery: [3, 4]
        bundle: [true, false]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Build JS
        run: npm run js

      - name: Lint JS
        run: npm run js-lint

      - name: Run unit tests
        env:
          JQUERY: ${{ matrix.jquery }}
          BUNDLE: ${{ matrix.bundle }}
        run: npm run test:unit
